apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mongo-tcp
  namespace: dev
spec:
  entryPoints:
    - mongodb
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mongo
          namespace: dev
          port: 27017