additionalArguments:
  - "--entryPoints.web.address=:80"
  - "--entryPoints.websecure.address=:443"
  - "--api.dashboard=true"
  - "--api.insecure=true"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"

ports:
  web:
    port: 80
    exposedPort: 80
    protocol: TCP
    expose:
      default: true

  websecure:
    port: 443
    exposedPort: 443
    protocol: TCP
    expose:
      default: true

service:
  enabled: true
  type: LoadBalancer

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik
