apiVersion: v2
name: ecommerce-category-service
description: A Helm chart for ecommerce-category-service
type: application
version: 0.0.12
appVersion: "0.0.11"

dependencies:
  - name: shared-helpers
    version: 0.1.0
    repository: "file://../shared-helpers"