architecture: replicaset
replicaCount: 1

auth:
  enabled: true
  rootUser: root
  rootPassword: rootpass

persistence:
  enabled: true
  size: 8Gi
  accessModes:
    - ReadWriteOnce
  deleteClaim: true

service:
  type: ClusterIP
  port: 27017
