apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-product-service-config
data:
  APP_ENV: {{ .Values.global.config.env }}
  MONGO_HOST: {{ .Values.global.config.mongo.host }}
  KAKFA_BROKERS: {{ .Values.global.config.kafka.brokers }}
