global:
  autoscaling:
    enabled: false
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  serviceAccount:
    create: false
  livenessProbe:
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
  configSuffix: "-config"

  config:
    env: "production"
    mongo:
      host: "mongo"
      password: "pass"
    kafka:
      brokers: "kafka:9092"

ecommerce-product-service:
  image:
    repository: sokol111/ecommerce-product-service
    tag: "0.0.13"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    host: ecommerce-product-service.localhost
    annotations: {}
  serviceAccount:
    create: false

ecommerce-category-service:
  image:
    repository: sokol111/ecommerce-category-service
    tag: "0.0.13"
    pullPolicy: IfNotPresent
  ingress:
    enabled: true
    host: ecommerce-category-service.localhost
    annotations: {}
  serviceAccount:
    create: false