global:
  autoscaling:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080
  serviceAccount:
    create: false
  ingress:
    enabled: true
    className: traefik
    annotations: {}
  livenessProbe:
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 2
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
  
  config:
    env: "production"
    mongo:
      host: "mongo"
      password: "pass"
    kafka:
      brokers: "kafka:9092"
