{{/*
  shared.deployment — template for Deployment

  Usage:
    {{ include "shared.deployment" (dict
      "name" (include "ecommerce-category-service.fullname" .)
      "Labels" (include "ecommerce-category-service.labels" . | fromYaml)
      "SelectorLabels" (include "ecommerce-category-service.selectorLabels" . | fromYaml)
      "Values" .Values
      "ServiceAccountName" (include "ecommerce-category-service.serviceAccountName" .)
      "Chart" .Chart
    ) }}


*/}}

{{- define "shared.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    {{- .Labels | nindent 4 }}
spec:
  {{- if not (or .Values.autoscaling.enabled .Values.global.autoscaling.enabled) }}
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .SelectorLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- .Labels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .ServiceAccountName }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.nameOverride | default .Values.chartName | default "app" }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default .Values.global.service.port }}
              protocol: TCP
          {{- with (.Values.livenessProbe | default .Values.global.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (.Values.readinessProbe | default .Values.global.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
