{{/*
  shared.deployment — template for Deployment

  Usage:
    {{ include "shared.deployment" (dict
      "name" (include "template.fullname" .)
      "Labels" (include "template.labels" . | fromYaml)
      "SelectorLabels" (include "template.selectorLabels" . | fromYaml)
      "Values" .Values
      "ServiceAccountName" (include "template.serviceAccountName" .)
      "Chart" .Chart
    ) }}


*/}}

{{- define "shared.deployment" -}}
{{- $autoscalingEnabled := and (.Values.autoscaling) (.Values.autoscaling.enabled) | default (.Values.global.autoscaling.enabled) }}
{{- $replicaCount := or .Values.replicaCount .Values.global.replicaCount }}
{{- $imagePullPolicy := and (.Values.image) (.Values.image.pullPolicy) | default .Values.global.image.pullPolicy }}
{{- $containerPort := and (.Values.service) (.Values.service.port) | default .Values.global.service.port }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    {{- toYaml .Labels | nindent 4 }}
spec:
  {{- if not $autoscalingEnabled }}
  replicas: {{ $replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- toYaml .SelectorLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- toYaml .Labels | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .ServiceAccountName | quote }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.nameOverride | default .Values.chartName | default "app" }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          envFrom:
            - configMapRef:
                name: {{ printf "%s%s" (include "template.name" .) .Values.global.configSuffix }}
          
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ $containerPort }}
              protocol: TCP
          {{- with (.Values.livenessProbe | default .Values.global.livenessProbe) }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with (.Values.readinessProbe | default .Values.global.readinessProbe) }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
