{{/*
  Shared ServiceAccount Template

  Usage:
    {{ include "shared.serviceAccount" (dict
      "name" (include "template.serviceAccountName" .)
      "Values" .Values
      "Labels" (include "template.labels" . | fromYaml)
    ) }}
*/}}

{{- define "shared.serviceAccount" -}}

{{- $sa := .Values.serviceAccount | default dict }}
{{- $gsa := .Values.global.serviceAccount | default dict }}

{{- $create := (hasKey .Values "serviceAccount") | ternary $sa.create $gsa.create }}
{{- if $create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
    {{- toYaml .Labels | nindent 4 }}
  {{- with ($sa.annotations | default $gsa.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automount | default $gsa.automount | default true }}
{{- end }}

{{- end }}
