{{/*
  Shared Service Template

  Usage:
    {{ include "shared.service" (dict
      "name" (include "template.fullname" .)
      "Values" .Values
      "Labels" (include "template.labels" . | fromYaml)
      "SelectorLabels" (include "template.selectorLabels" . | fromYaml)
    ) }}
*/}}

{{- define "shared.service" -}}

{{- $values := .Values }}
{{- $global := .Values.global }}
{{- $service := or $values.service $global.service }}

{{- $type := and $service $service.type | default "ClusterIP" }}
{{- $port := and $service $service.port | default 80 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- toYaml .Labels | nindent 4 }}
spec:
  type: {{ $type }}
  ports:
    - port: {{ $port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- toYaml .SelectorLabels | nindent 4 }}
{{- end }}
