name: Build JS API

on:
  workflow_call:
    inputs:
      artifact_dir:
        required: true
        type: string
      artifact:
        required: true
        type: string
      openapi_file:
        required: true
        type: string
      version:
        required: true
        type: string
      npm_repo_name:
        required: true
        type: string
      project_name:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download build-js-api.mk
        run: curl -sSfL https://raw.githubusercontent.com/Sokol111/ecommerce-infrastructure/master/makefiles/build-js-api.mk -o build-js-api.mk

      - name: Build JavaScript SDK
        run: make -f build-js-api.mk build-js-api
        env:
          JS_GEN_DIR: ${{ inputs.artifact_dir }}
          OPENAPI_FILE: ${{ inputs.openapi_file }}
          PROJECT_NAME: ${{ inputs.project_name }}
          NPM_PACKAGE_NAME: ${{ inputs.npm_repo_name }}
          AUTHOR: ${{ github.repository_owner }}
          REPOSITORY_URL: "https://github.com/${{ github.repository }}.git"
          VERSION: ${{ inputs.version }}

      - name: Upload built JS API
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifact_dir }}
