name: Build and release GO service

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image.outputs.image_name }}
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - id: image
        run: echo "image_name=sokol111/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT

      - id: tag
        run: echo "image_tag=${GITHUB_EVENT_INPUTS_VERSION#v}" >> $GITHUB_OUTPUT
        env:
          GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}

  debug-outputs:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: |
          echo "image_name: ${{ needs.prepare.outputs.image_name }}"
          echo "image_tag: ${{ needs.prepare.outputs.image_tag }}"

  build-docker-image:
    needs: prepare
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/build-docker-image.yml@master
    with:
      dockerfile: Dockerfile.go
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release-tag:
    needs: [prepare, build-docker-image]
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/release-tag.yml@master
    with:
      version: ${{ github.event.inputs.version }}

  publish-docker:
    needs: [prepare, build-docker-image, release-tag]
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/publish-docker.yml@master
    with:
      image_name: ${{ needs.prepare.outputs.image_name }}
      tag: ${{ needs.prepare.outputs.image_tag }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
