name: Build Docker Image

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout infra
        uses: actions/checkout@v4
        with:
          repository: Sokol111/ecommerce-infrastructure
          path: infra

      - name: Prepare dockerfile path
        id: prepare
        run: echo "DOCKERFILE_PATH=infra/docker/${{ inputs.dockerfile }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker cache
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles(env.DOCKERFILE_PATH) }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Registry (for cache only)
        uses: docker/login-action@v3
        with:
          username: sokol111
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (no push)
        run: |
          docker buildx build \
            -f $DOCKERFILE_PATH \
            -t image:temp \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            --load .

      - name: Save Docker image to tarball
        run: docker save -o image.tar image:temp

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
