name: Build and release GO service

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
      image_name: ${{ steps.meta.outputs.image_name }}
      image_tag: ${{ steps.meta.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - id: meta
        run: |
          VERSION_INPUT="${{ inputs.version }}"
          if [ -z "$VERSION_INPUT" ]; then
            VERSION_INPUT=$(cat VERSION | tr -d '\n' | tr -d '\r')
            VERSION_INPUT="v$VERSION_INPUT"
          fi
          IMAGE_NAME=sokol111/$(basename ${GITHUB_REPOSITORY})
          IMAGE_TAG="${VERSION_INPUT#v}"

          echo "version=$VERSION_INPUT" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

          echo "Extracted version: $VERSION_INPUT"
          echo "Extracted image_name: $IMAGE_NAME"
          echo "Extracted image_tag: $IMAGE_TAG"

  build-docker-image:
    needs: prepare
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/build-docker-image.yml@master
    with:
      dockerfile: Dockerfile.go
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release-tag:
    needs: [prepare, build-docker-image]
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/release-tag.yml@master
    with:
      version: ${{ needs.prepare.outputs.version }}

  publish-docker:
    needs: [prepare, build-docker-image, release-tag]
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/publish-docker.yml@master
    with:
      image_name: ${{ needs.prepare.outputs.image_name }}
      tag: ${{ needs.prepare.outputs.image_tag }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
