name: Build and release GO and JS API

on:
  workflow_call:
    inputs:
      openapi_file:
        required: false
        type: string
      version:
        required: false
        type: string
      npm_repo_name:
        required: false
        type: string
      project_name:
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      openapi_file: ${{ steps.openapi.outputs.openapi_file }}
      version: ${{ steps.ver.outputs.version }}
      npm_repo_name: ${{ steps.repo.outputs.npm_repo_name }}
      project_name: ${{ steps.proj.outputs.project_name }}
      go_gen_dir: api
      go_package: api
      go_artifact: go-api
      js_gen_dir: js-client
      js_artifact: js-api

    steps:
      - uses: actions/checkout@v4

      - id: openapi
        run: |
          if [ -z "${{ inputs.openapi_file }}" ]; then
            echo "openapi_file=openapi/openapi.yml" >> $GITHUB_OUTPUT
          else
            echo "openapi_file=${{ inputs.openapi_file }}" >> $GITHUB_OUTPUT
          fi

      - id: ver
        env:
          OPENAPI_FILE: ${{ steps.openapi.outputs.openapi_file }}
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            echo "version=v$(yq e '.info.version' $OPENAPI_FILE)" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - id: repo
        run: |
          if [ -z "${{ inputs.npm_repo_name }}" ]; then
            echo "npm_repo_name=@${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          else
            echo "npm_repo_name=${{ inputs.npm_repo_name }}" >> $GITHUB_OUTPUT
          fi

      - id: proj
        run: |
          if [ -z "${{ inputs.project_name }}" ]; then
            echo "project_name=$(basename '${GITHUB_REPOSITORY}')" >> $GITHUB_OUTPUT
          else
            echo "project_name=${{ inputs.project_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Debug outputs
        run: |
          echo "Final version: ${{ steps.ver.outputs.version }}"
          echo "Final openapi_file: ${{ steps.openapi.outputs.openapi_file }}"

  debug-outputs:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Print outputs
        run: |
          echo "version: ${{ needs.prepare.outputs.version }}"
          echo "openapi_file: ${{ needs.prepare.outputs.openapi_file }}"
          echo "npm_repo_name: ${{ needs.prepare.outputs.npm_repo_name }}"
          echo "project_name: ${{ needs.prepare.outputs.project_name }}"

  build-go-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/build-go-api.yml@master
    needs: prepare
    with:
      openapi_file: ${{ needs.prepare.outputs.openapi_file }}
      artifact: ${{ needs.prepare.outputs.go_artifact }}
      artifact_dir: ${{ needs.prepare.outputs.go_gen_dir }}
      package: ${{ needs.prepare.outputs.go_package }}

  build-js-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/build-js-api.yml@master
    needs: prepare
    with:
      artifact_dir: ${{ needs.prepare.outputs.js_gen_dir }}
      artifact: ${{ needs.prepare.outputs.js_artifact }}
      openapi_file: ${{ needs.prepare.outputs.openapi_file }}
      version: ${{ needs.prepare.outputs.version }}
      npm_repo_name: ${{ needs.prepare.outputs.npm_repo_name }}
      project_name: ${{ needs.prepare.outputs.project_name }}

  release-go-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/release-tag.yml@master
    needs: [prepare, generate-go-api, generate-js-api]
    with:
      version: ${{ needs.prepare.outputs.version }}
      artifact_dir: ${{ needs.prepare.outputs.go_gen_dir }}
      artifact: ${{ needs.prepare.outputs.go_artifact }}

  publish-js-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/publish-js.yml@master
    needs: [prepare, generate-go-api, generate-js-api, release-go-api]
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      artifact_dir: ${{ needs.prepare.outputs.js_gen_dir }}
      artifact: ${{ needs.prepare.outputs.js_artifact }}
