name: Build Go API

on:
  workflow_call:
    inputs:
      openapi_file:
        required: true
        type: string
      artifact:
        required: true
        type: string
      artifact_dir:
        required: true
        type: string
      package:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Download build-go-api.mk
        run: curl -sSfL https://raw.githubusercontent.com/Sokol111/ecommerce-infrastructure/master/makefiles/build-go-api.mk -o build-go-api.mk

      - name: Init Go module
        run: go mod init github.com/${{ github.repository }}

      - name: Build Go API
        run: make -f build-go-api.mk build-go-api
        env:
          OPENAPI_FILE: ${{ inputs.openapi_file }}
          GO_GEN_DIR: ${{ inputs.artifact_dir }}
          PACKAGE: ${{ inputs.package }}

      - name: Upload built Go API
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifact_dir }}
