name: Build and push go docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: latest
    secrets:
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout microservice
        uses: actions/checkout@v4

      - name: Checkout infrastructure repo
        uses: actions/checkout@v4
        with:
          repository: Sokol111/ecommerce-infrastructure
          path: infra

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: sokol111
          password: ${{ secrets.registry_password }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            -f infra/docker/Dockerfile.buildkit \
            -t ${{ inputs.image_name }}:${{ inputs.tag }} \
            --push .
