name: Generate and Release GO and JS API

on:
  workflow_call:
    inputs:
      openapi_file:
        required: false
        type: string
      version:
        required: false
        type: string
      npm_repo_name:
        required: false
        type: string
      project_name:
        required: false
        type: string
    secrets:
      NPM_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      openapi_file: ${{ steps.openapi.outputs.openapi_file }}
      version: ${{ steps.ver.outputs.version }}
      npm_repo_name: ${{ steps.repo.outputs.npm_repo_name }}
      project_name: ${{ steps.proj.outputs.project_name }}
      go_gen_dir: api
      go_package: api
      js_gen_dir: js-client

    steps:
      - uses: actions/checkout@v4

      - id: openapi
        run: |
          if [ -z "${{ inputs.openapi_file }}" ]; then
            echo "openapi_file=openapi/openapi.yml" >> $GITHUB_OUTPUT
          else
            echo "openapi_file=${{ inputs.openapi_file }}" >> $GITHUB_OUTPUT
          fi

      - id: ver
        env:
          OPENAPI_FILE: ${{ steps.openapi.outputs.openapi_file }}
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            echo "version=v$(yq e '.info.version' $OPENAPI_FILE)" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - id: repo
        run: |
          if [ -z "${{ inputs.npm_repo_name }}" ]; then
            echo "npm_repo_name=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT
          else
            echo "npm_repo_name=${{ inputs.npm_repo_name }}" >> $GITHUB_OUTPUT
          fi

      - id: proj
        run: |
          if [ -z "${{ inputs.project_name }}" ]; then
            echo "project_name=$(basename '${GITHUB_REPOSITORY}')" >> $GITHUB_OUTPUT
          else
            echo "project_name=${{ inputs.project_name }}" >> $GITHUB_OUTPUT
          fi

  generate-go-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/generate-go-api.yml@master
    needs: prepare
    with:
      openapi_file: ${{ needs.prepare.outputs.openapi_file }}
      go_gen_dir: ${{ needs.prepare.outputs.go_gen_dir }}
      package: ${{ needs.prepare.outputs.go_package }}

  generate-js-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/generate-js-api.yml@master
    needs: prepare
    with:
      js_gen_dir: ${{ needs.prepare.outputs.js_gen_dir }}
      openapi_file: ${{ needs.prepare.outputs.openapi_file }}
      version: ${{ needs.prepare.outputs.version }}
      npm_repo_name: ${{ needs.prepare.outputs.npm_repo_name }}
      project_name: ${{ needs.prepare.outputs.project_name }}

  release-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/release-api.yml@master
    needs: [generate-go-api, generate-js-api]
    with:
      version: ${{ needs.prepare.outputs.version }}
      paths_to_commit: ${{ needs.prepare.outputs.go_gen_dir }}

  publish-js-api:
    uses: Sokol111/ecommerce-infrastructure/.github/workflows/publish-js-api.yml@master
    needs: release-api
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      js_gen_dir: ${{ needs.prepare.outputs.js_gen_dir }}
