name: Publish JS to npm

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
    inputs:
      artifact_dir:
        required: true
        type: string
      artifact:
        required: true
        type: string

jobs:
  publish-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download JS artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifact_dir }}

      - name: Publish to npm
        run: |
          cd ${{ inputs.artifact_dir }}
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
