name: Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      REGISTRY_PASSWORD:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image from tarball
        run: |
          docker load -i image.tar

      - name: Tag Docker image
        run: |
          docker tag ${{ inputs.image_name }}:temp ${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: sokol111
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ inputs.image_name }}:${{ inputs.tag }}
