name: Create GitHub Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
