name: Release GO API

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      go_gen_dir:
        required: true
        type: string
      go_artifact:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Inputs
        run: |
          echo "version: ${{ inputs.version }}"
          echo "go_gen_dir: ${{ inputs.go_gen_dir }}"
          echo "go_artifact: ${{ inputs.go_artifact }}"

      - name: Check if tag already exists
        run: |
          if git rev-parse "refs/tags/${{ inputs.version }}" >/dev/null 2>&1; then
            echo "❌ Tag ${{ inputs.version }} already exists"
            exit 1
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download Go API
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.go_artifact }}
          path: ${{ inputs.go_gen_dir }}

      - name: Commit GO API to `generated` branch
        run: |
          git checkout -B generated
          git add -f ${{ inputs.go_gen_dir }}
          git commit -m "Generate API for release ${{ inputs.version }}" || echo "No changes to commit"
          git push -u origin generated --force

      - name: Tag release
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            echo "❌ No version provided"
            exit 1
          fi

          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: |
            API generated automatically for version ${{ inputs.version }}.
